In [1]:
#sort , search & Counting Function

In [2]:
import numpy as np

In [4]:
arr = np.array([4,3,6,7,56,45,78,5,2,9,4,7,78])

In [5]:
arr

array([ 4,  3,  6,  7, 56, 45, 78,  5,  2,  9,  4,  7, 78])

In [6]:
np.sort(arr)

array([ 2,  3,  4,  4,  5,  6,  7,  7,  9, 45, 56, 78, 78])

In [7]:
np.searchsorted(arr , 45)

4

In [9]:
arr1 = np.array([0,74,5,4,0,0,56,0,0,0,1,5])

In [10]:
arr1

array([ 0, 74,  5,  4,  0,  0, 56,  0,  0,  0,  1,  5])

In [11]:
np.count_nonzero(arr1)

6

In [13]:
arr

array([ 4,  3,  6,  7, 56, 45, 78,  5,  2,  9,  4,  7, 78])

In [14]:
np.where(arr > 6)

(array([ 3,  4,  5,  6,  9, 11, 12]),)

In [15]:
np.extract(arr>6 , arr)

array([ 7, 56, 45, 78,  9,  7, 78])

In [16]:
# Byte swapping

In [17]:
arr

array([ 4,  3,  6,  7, 56, 45, 78,  5,  2,  9,  4,  7, 78])

In [18]:
arr.byteswap()

array([ 288230376151711744,  216172782113783808,  432345564227567616,
        504403158265495552, 4035225266123964416, 3242591731706757120,
       5620492334958379008,  360287970189639680,  144115188075855872,
        648518346341351424,  288230376151711744,  504403158265495552,
       5620492334958379008])

In [19]:
#Copies & Views

In [20]:
arr

array([ 4,  3,  6,  7, 56, 45, 78,  5,  2,  9,  4,  7, 78])

In [21]:
a = np.copy(arr)

In [22]:
b= arr.view()

In [28]:
b = arr

In [23]:
b

array([ 4,  3,  6,  7, 56, 45, 78,  5,  2,  9,  4,  7, 78])

In [24]:
arr

array([ 4,  3,  6,  7, 56, 45, 78,  5,  2,  9,  4,  7, 78])

In [25]:
b[0] = 35

In [26]:
b

array([35,  3,  6,  7, 56, 45, 78,  5,  2,  9,  4,  7, 78])

In [27]:
arr

array([35,  3,  6,  7, 56, 45, 78,  5,  2,  9,  4,  7, 78])

In [29]:
# Matrix Library

In [30]:
import numpy.matlib as ma

In [33]:
ma.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [34]:
ma.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [35]:
ma.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [36]:
# numpy - Linear Algebra

In [37]:
arr1 = np.random.randint([[2,3] , [4,5]])

In [38]:
arr2 = np.random.randint([[5,3] , [2,5]])

In [39]:
np.dot(arr1 , arr2)

array([[ 0,  0],
       [ 0, 12]])

In [40]:
arr1 @ arr2

array([[ 0,  0],
       [ 0, 12]])