In [61]:
#numpy array maipulation

In [62]:
import numpy as np

In [63]:
arr = np.random.randint(1,10,(3,4))

In [64]:
arr

array([[4, 7, 5, 8],
       [2, 4, 7, 6],
       [5, 1, 5, 1]])

In [5]:
arr.reshape(6,2)

array([[7, 5],
       [2, 6],
       [7, 5],
       [2, 4],
       [1, 3],
       [4, 7]])

In [7]:
arr.reshape(2,6)

array([[7, 5, 2, 6, 7, 5],
       [2, 4, 1, 3, 4, 7]])

In [9]:
arr.reshape(2,-5588454)

array([[7, 5, 2, 6, 7, 5],
       [2, 4, 1, 3, 4, 7]])

In [10]:
arr 

array([[7, 5, 2, 6],
       [7, 5, 2, 4],
       [1, 3, 4, 7]])

In [11]:
arr.T

array([[7, 7, 1],
       [5, 5, 3],
       [2, 2, 4],
       [6, 4, 7]])

In [12]:
arr

array([[7, 5, 2, 6],
       [7, 5, 2, 4],
       [1, 3, 4, 7]])

In [13]:
arr.flatten()

array([7, 5, 2, 6, 7, 5, 2, 4, 1, 3, 4, 7])

In [65]:
arr1 = np.array([1,2,3,3,4])

In [15]:
arr1.ndim

1

In [19]:
np.expand_dims(arr1 , axis= 1)

array([[1],
       [2],
       [3],
       [3],
       [4]])

In [20]:
np.expand_dims(arr1 , axis= 0)

array([[1, 2, 3, 3, 4]])

In [21]:
arr

array([[7, 5, 2, 6],
       [7, 5, 2, 4],
       [1, 3, 4, 7]])

In [22]:
np.squeeze(arr)

array([[7, 5, 2, 6],
       [7, 5, 2, 4],
       [1, 3, 4, 7]])

In [23]:
data = np.array([[1],[2],[3]])

In [24]:
data

array([[1],
       [2],
       [3]])

In [25]:
np.squeeze(data)

array([1, 2, 3])

In [26]:
arr1

array([1, 2, 3, 3, 4])

In [27]:
np.repeat(arr1, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4])

In [30]:
np.roll(arr1 , 2)

array([3, 4, 1, 2, 3])

In [31]:
arr1

array([1, 2, 3, 3, 4])

In [32]:
np.diag(arr1)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [33]:
#numpy binary operation

In [67]:
arr1 = np.random.randint(1,10,(3,4))

In [39]:
arr2 = np.random.randint(1,10,(3,4))

In [40]:
arr1

array([[2, 3, 1, 9],
       [2, 2, 5, 1],
       [9, 5, 5, 1]])

In [41]:
arr2

array([[7, 9, 5, 5],
       [8, 6, 3, 4],
       [1, 2, 6, 7]])

In [42]:
arr1 + arr2

array([[ 9, 12,  6, 14],
       [10,  8,  8,  5],
       [10,  7, 11,  8]])

In [43]:
arr1 * arr2

array([[14, 27,  5, 45],
       [16, 12, 15,  4],
       [ 9, 10, 30,  7]])

In [44]:
arr1 / arr2

array([[0.28571429, 0.33333333, 0.2       , 1.8       ],
       [0.25      , 0.33333333, 1.66666667, 0.25      ],
       [9.        , 2.5       , 0.83333333, 0.14285714]])

In [45]:
arr1 - arr2

array([[-5, -6, -4,  4],
       [-6, -4,  2, -3],
       [ 8,  3, -1, -6]])

In [46]:
arr1 % arr2

array([[2, 3, 1, 4],
       [2, 2, 2, 1],
       [0, 1, 5, 1]])

In [47]:
arr1 ** arr2

array([[  128, 19683,     1, 59049],
       [  256,    64,   125,     1],
       [    9,    25, 15625,     1]])

In [48]:
arr1 & arr2

array([[2, 1, 1, 1],
       [0, 2, 1, 0],
       [1, 0, 4, 1]])

In [49]:
arr1

array([[2, 3, 1, 9],
       [2, 2, 5, 1],
       [9, 5, 5, 1]])

In [50]:
arr2

array([[7, 9, 5, 5],
       [8, 6, 3, 4],
       [1, 2, 6, 7]])

In [51]:
-arr1

array([[-2, -3, -1, -9],
       [-2, -2, -5, -1],
       [-9, -5, -5, -1]])

In [52]:
arr1| arr2

array([[ 7, 11,  5, 13],
       [10,  6,  7,  5],
       [ 9,  7,  7,  7]])

In [53]:
arr1 > arr2

array([[False, False, False,  True],
       [False, False,  True, False],
       [ True,  True, False, False]])

In [54]:
#numpy String function

In [56]:
arr = np.array(["santosh" , "maurya"])

In [57]:
arr

array(['santosh', 'maurya'], dtype='<U7')

In [58]:
np.char.upper(arr)

array(['SANTOSH', 'MAURYA'], dtype='<U7')

In [59]:
np.char.title(arr)

array(['Santosh', 'Maurya'], dtype='<U7')

In [60]:
np.char.capitalize(arr)

array(['Santosh', 'Maurya'], dtype='<U7')

In [ ]:
#numpy mathematical Function

In [68]:
arr1

array([[6, 6, 4, 5],
       [4, 1, 6, 1],
       [5, 2, 8, 3]])

In [69]:
np.sin(arr1)

array([[-0.2794155 , -0.2794155 , -0.7568025 , -0.95892427],
       [-0.7568025 ,  0.84147098, -0.2794155 ,  0.84147098],
       [-0.95892427,  0.90929743,  0.98935825,  0.14112001]])

In [72]:
np.cos(arr1)

array([[ 0.96017029,  0.96017029, -0.65364362,  0.28366219],
       [-0.65364362,  0.54030231,  0.96017029,  0.54030231],
       [ 0.28366219, -0.41614684, -0.14550003, -0.9899925 ]])

In [74]:
np.tan(arr1)

array([[-0.29100619, -0.29100619,  1.15782128, -3.38051501],
       [ 1.15782128,  1.55740772, -0.29100619,  1.55740772],
       [-3.38051501, -2.18503986, -6.79971146, -0.14254654]])

In [75]:
np.tanh(arr1)

array([[0.99998771, 0.99998771, 0.9993293 , 0.9999092 ],
       [0.9993293 , 0.76159416, 0.99998771, 0.76159416],
       [0.9999092 , 0.96402758, 0.99999977, 0.99505475]])

In [76]:
np.log10(arr1)

array([[0.77815125, 0.77815125, 0.60205999, 0.69897   ],
       [0.60205999, 0.        , 0.77815125, 0.        ],
       [0.69897   , 0.30103   , 0.90308999, 0.47712125]])

In [77]:
np.exp(arr1)

array([[4.03428793e+02, 4.03428793e+02, 5.45981500e+01, 1.48413159e+02],
       [5.45981500e+01, 2.71828183e+00, 4.03428793e+02, 2.71828183e+00],
       [1.48413159e+02, 7.38905610e+00, 2.98095799e+03, 2.00855369e+01]])

In [78]:
np.sqrt(arr1)

array([[2.44948974, 2.44948974, 2.        , 2.23606798],
       [2.        , 1.        , 2.44948974, 1.        ],
       [2.23606798, 1.41421356, 2.82842712, 1.73205081]])

In [79]:
np.power(arr1, 2)

array([[36, 36, 16, 25],
       [16,  1, 36,  1],
       [25,  4, 64,  9]])

In [80]:
np.mean(arr1)

4.25

In [81]:
np.min(arr1)

1

In [82]:
np.median(arr1)

4.5

In [83]:
np.std(arr1)

2.0866640042581523

In [84]:
np.var(arr1)

4.354166666666667

In [85]:
np.max(arr1)

8