In [1]:
import numpy as np

In [2]:
l = [1,2,3,4]

In [3]:
ar = np.array(l)

In [4]:
ar

array([1, 2, 3, 4])

In [5]:
type(ar)

numpy.ndarray

In [6]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [7]:
np.asarray(l)

array([1, 2, 3, 4])

In [8]:
a = [2,3,4]

In [9]:
np.asanyarray(a)

array([2, 3, 4])

In [10]:
b = np.matrix(l)

In [11]:
b

matrix([[1, 2, 3, 4]])

In [12]:
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [13]:
a = np.array(l)

In [14]:
a

array([1, 2, 3, 4])

In [15]:
c= a

In [16]:
c

array([1, 2, 3, 4])

In [17]:
a

array([1, 2, 3, 4])

In [18]:
c[0]

1

In [19]:
c[0] = 100

In [20]:
c

array([100,   2,   3,   4])

In [21]:
a

array([100,   2,   3,   4])

In [22]:
d = np.copy(a)

In [23]:
d

array([100,   2,   3,   4])

In [24]:
a[1] = 400

In [25]:
a

array([100, 400,   3,   4])

In [26]:
d

array([100,   2,   3,   4])

In [27]:
np.fromfunction(lambda i , j : i == j , (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [28]:
np.fromfunction(lambda i , j : i * j , (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [29]:
iterable = (i*i for i in range(5))

In [30]:
np.fromiter(iterable ,int)

array([ 0,  1,  4,  9, 16])

In [31]:
np.fromstring('125 456' , sep = ' ')

array([125., 456.])

In [32]:
np.fromstring('4,5' , sep = ' , ')

array([4., 5.])

In [33]:
#Numpy - Data types

In [34]:
l = [2,3,4,5,6]

In [35]:
ar = np.array(l)

In [36]:
ar

array([2, 3, 4, 5, 6])

In [37]:
ar.ndim

1

In [38]:
ar2 =  np.array([[1,2,3,4] , [2,3,4,5]])

In [39]:
ar2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [40]:
ar2.ndim

2

In [41]:
ar.size

5

In [42]:
ar2.size

8

In [43]:
ar

array([2, 3, 4, 5, 6])

In [44]:
ar2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [45]:
ar.shape

(5,)

In [46]:
ar2.shape

(2, 4)

In [47]:
ar.dtype

dtype('int64')

In [48]:
ar2.dtype

dtype('int64')

In [49]:
ar22 = np.array([(1.4,56,45),(25,45,66)])

In [50]:
ar22

array([[ 1.4, 56. , 45. ],
       [25. , 45. , 66. ]])

In [51]:
ar22.dtype

dtype('float64')

In [52]:
list(range(5))

[0, 1, 2, 3, 4]

In [53]:
np.arange(2.3,5.6)

array([2.3, 3.3, 4.3, 5.3])

In [54]:
list(np.arange(2.3,5.6,.3))

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [55]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [56]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [58]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [59]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [60]:
np.zeros((3,4,2,3))

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [61]:
ar4 = np.zeros((3,4,2,3))

In [62]:
ar4

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [63]:
np.ones(4)

array([1., 1., 1., 1.])

In [65]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [67]:
on = np.ones((2,3,2))

In [68]:
on

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [69]:
on + 5

array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [70]:
on * 4

array([[[4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.]]])

In [74]:
np.empty((3,6))

array([[0., 0., 0., 1., 1., 1.],
       [2., 2., 2., 0., 1., 2.],
       [0., 1., 2., 0., 1., 2.]])

In [75]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [76]:
np.linspace(2,4,20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [77]:
np.logspace(2,5,10)

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [78]:
np.logspace(2,5,10 , base = 2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [80]:
arr = np.random.randn(3,4)

In [81]:
import pandas as pd 

In [82]:
pd.DataFrame(arr)

0         1         2         3
0  2.185081  0.599830  0.208088 -0.312134
1  0.774286  0.218713 -0.278419 -0.994401
2  0.853218  0.356772 -0.223240  0.418347

In [83]:
np.random.rand(3,4)

array([[0.07841619, 0.6737957 , 0.99335798, 0.58044568],
       [0.22053351, 0.15990384, 0.56739882, 0.15463373],
       [0.8966651 , 0.15663264, 0.86672853, 0.53939318]])

In [88]:
pd.DataFrame(np.random.randint(1,110, (300,400))).to_csv('test.csv')

In [89]:
arr = np.random.rand(3,4)

In [90]:
arr

array([[0.00702905, 0.30701137, 0.50421344, 0.2330905 ],
       [0.21334773, 0.21618592, 0.70755652, 0.82104891],
       [0.09386579, 0.2538998 , 0.56854328, 0.03291636]])

In [92]:
arr1 = arr.reshape(6,2)

In [93]:
arr1

array([[0.00702905, 0.30701137],
       [0.50421344, 0.2330905 ],
       [0.21334773, 0.21618592],
       [0.70755652, 0.82104891],
       [0.09386579, 0.2538998 ],
       [0.56854328, 0.03291636]])

In [95]:
arr1[1][1]

0.2330904952500119

In [97]:
arr1[2:5,1]

array([0.21618592, 0.82104891, 0.2538998 ])

In [4]:
arr = np.random.randint(1,100,(5,5))

In [5]:
arr

array([[46, 74, 94, 82, 27],
       [69, 79, 81, 44, 24],
       [12, 84,  4, 69, 48],
       [50, 25, 87, 95, 79],
       [ 7, 89, 46, 56, 15]])

In [7]:
arr[arr > 50]

array([74, 94, 82, 69, 79, 81, 84, 69, 87, 95, 79, 89, 56])

In [8]:
arr

array([[46, 74, 94, 82, 27],
       [69, 79, 81, 44, 24],
       [12, 84,  4, 69, 48],
       [50, 25, 87, 95, 79],
       [ 7, 89, 46, 56, 15]])

In [9]:
arr[2:4 , [1,2]]

array([[84,  4],
       [25, 87]])

In [11]:
arr[0][0] = 5000

In [12]:
arr

array([[5000,   74,   94,   82,   27],
       [  69,   79,   81,   44,   24],
       [  12,   84,    4,   69,   48],
       [  50,   25,   87,   95,   79],
       [   7,   89,   46,   56,   15]])

In [13]:
arr1 = np.random.randint(1,3 ,(3,3))
arr2 = np.random.randint(1,3 ,(3,3))

In [14]:
arr1

array([[1, 2, 1],
       [2, 1, 1],
       [1, 2, 1]])

In [15]:
arr2

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 1]])

In [16]:
arr1 + arr2

array([[3, 4, 3],
       [4, 3, 3],
       [3, 4, 2]])

In [17]:
arr1 - arr2

array([[-1,  0, -1],
       [ 0, -1, -1],
       [-1,  0,  0]])

In [18]:
arr1 / arr2

array([[0.5, 1. , 0.5],
       [1. , 0.5, 0.5],
       [0.5, 1. , 1. ]])

In [19]:
arr1 * arr2

array([[2, 4, 2],
       [4, 2, 2],
       [2, 4, 1]])

In [20]:
arr1 @ arr2

array([[8, 8, 7],
       [8, 8, 7],
       [8, 8, 7]])

In [21]:
arr1 / 0

/tmp/ipykernel_1020/824215542.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1 / 0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [22]:
arr1 + 100

array([[101, 102, 101],
       [102, 101, 101],
       [101, 102, 101]])

In [23]:
arr1 ** 2

array([[1, 4, 1],
       [4, 1, 1],
       [1, 4, 1]])

In [24]:
# Numpy - Broadcasting

In [2]:
arr = np.zeros((4,4))

In [3]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
row = np.array([1,2,3,4])

In [5]:
row

array([1, 2, 3, 4])

In [6]:
arr+ row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [7]:
row.shape

(4,)

In [8]:
row.T

array([1, 2, 3, 4])

In [10]:
col = np.array([[1,2,3,4]])

In [11]:
col.T

array([[1],
       [2],
       [3],
       [4]])

In [13]:
col.T + arr

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [14]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
arr1 = np.random.randint(1,4,(3,4))

In [17]:
arr1

array([[3, 2, 3, 2],
       [2, 3, 3, 3],
       [1, 2, 2, 2]])

In [19]:
np.sqrt(arr1)

array([[1.73205081, 1.41421356, 1.73205081, 1.41421356],
       [1.41421356, 1.73205081, 1.73205081, 1.73205081],
       [1.        , 1.41421356, 1.41421356, 1.41421356]])

In [20]:
np.exp(arr1)

array([[20.08553692,  7.3890561 , 20.08553692,  7.3890561 ],
       [ 7.3890561 , 20.08553692, 20.08553692, 20.08553692],
       [ 2.71828183,  7.3890561 ,  7.3890561 ,  7.3890561 ]])

In [21]:
np.log10(arr1)

array([[0.47712125, 0.30103   , 0.47712125, 0.30103   ],
       [0.30103   , 0.47712125, 0.47712125, 0.47712125],
       [0.        , 0.30103   , 0.30103   , 0.30103   ]])